In [1]:
import numpy as np

import time
import cv2

In [2]:
def brightPassFilter(image, thresh):
    
    imgx = image.shape[0]
    imgy = image.shape[1]
    
    #this is how you create a new np array!! Don't use '='
    edit = np.copy(image)
    
    for i in range(0, imgx):
        for j in range(0, imgy):
            if image[i][j][0] < thresh and image[i][j][1] < thresh and image[i][j][2] < thresh:
                edit[i][j] = 0
                
    return edit
    
def bloom(image, thresh, blurx, blury):
    
    imgBrightPass = brightPassFilter(image, thresh)
    
    imgBlur = cv2.blur(imgBrightPass, (blurx, blury))

    bloom = cv2.addWeighted(imgBlur, 1, img, 1, 0)
    
    return bloom


#start of program
img = cv2.imread('city.jpg')

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

for i in range(0,1):
    img = bloom(img, 150, 10, 10)

                
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


    

In [68]:

#this block creates weird rectangles around bright spots on the image
def brightPassFilter(image, thresh):
    
    imgx = image.shape[0]
    imgy = image.shape[1]
    
    #this is how you create a new np array!! Don't use '='
    edit = np.copy(image)
    
    for i in range(0, imgx):
        for j in range(0, imgy):
            if image[i][j][0] < thresh and image[i][j][1] < thresh and image[i][j][2] < thresh:
                edit[i][j] = 0
                
    return edit

def blendIgnoreBlack(img1, img2):
    
    imgx = img1.shape[0]
    imgy = img1.shape[1]
    
    edit = np.copy(img1)
    
    for i in range(0, imgx):
        for j in range(0, imgy):
            if img1[i][j][0] != 0 and img1[i][j][1] != 0 and img1[i][j][2] != 0:
                edit[i][j][0] = (img1[i][j][0] + img2[i][j][0] % 256)
                edit[i][j][1] = (img1[i][j][1] + img2[i][j][1] % 256)
                edit[i][j][2] = (img1[i][j][2] + img2[i][j][2] % 256)
                
    return edit
    



img = cv2.imread('city.jpg')
        
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

imgBright = brightPassFilter(img, 200)
    
imgBlur = cv2.blur(imgBrightPass, (10,10))

bloom = blendIgnoreBlack(imgBlur,img)


cv2.imshow('img', img)
cv2.imshow('brightpass', imgBrightPass)
cv2.imshow('blur', imgBlur)
cv2.imshow('bloom', bloom)
cv2.waitKey(0)
cv2.destroyAllWindows()
    


    




[[[ 45  41  40]
  [ 43  39  38]
  [ 45  41  40]
  ..., 
  [ 53  41  29]
  [ 53  39  21]
  [111  96  77]]

 [[ 49  45  44]
  [ 48  44  43]
  [ 49  46  42]
  ..., 
  [ 57  45  33]
  [ 53  39  21]
  [107  92  73]]

 [[ 49  46  42]
  [ 51  48  44]
  [ 48  45  41]
  ..., 
  [ 54  43  29]
  [ 52  38  20]
  [109  94  75]]

 ..., 
 [[125 119 120]
  [117 111 112]
  [105 100 101]
  ..., 
  [122 121 123]
  [149 148 150]
  [128 127 129]]

 [[ 98  92  93]
  [ 95  89  90]
  [115 109 110]
  ..., 
  [142 141 143]
  [135 134 136]
  [119 118 120]]

 [[117 109 109]
  [111 105 106]
  [117 111 112]
  ..., 
  [141 140 142]
  [143 142 144]
  [135 134 136]]]


In [ ]:
def vertEdgeDetect(img):
    vertMask = np.array([[0,255,0],
                     [0,255,0],
                     [0,255,0]])

    imgx = img.shape[0]
    imgy = img.shape[1]

    img = cv2.copyMakeBorder(img, 10, 10, 10, 10, cv2.BORDER_CONSTANT)


    for i in range(0, imgx):
        for j in range(0, imgy):
            if np.array_equal(img[i:i+2][j:j+2], vertMask):
                img[i+1][j+1] = 0
            else:
                img[i+1][j+1] = 255
            
            
    cv2.imshow('image', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
'''
um = img[:, 300]
print um
for i in range(0, 300):
    img[: , i] = um
    
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
'''
